name: Hello World App Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Banner
        run: echo "=== Hello World App Debug ==="

      - name: Show IDs
        run: |
          echo "App ID: ${{ secrets.CLAUDE_AI_APP_ID }}"
          echo "Installation ID: ${{ secrets.CLAUDE_AI_INSTALLATION_ID }}"
          echo "Done."
