name: LearnStream Claude AI (PR/Issue/Comment)

on:
  workflow_dispatch:
    inputs:
      action:
        description: "open-issue | pr-comment | issue-comment | pr-code | open-pr"
        required: true
        type: choice
        options: [open-issue, pr-comment, issue-comment, pr-code, open-pr]
      target_repo:
        description: "owner/repo (defaults to current)"
        required: false
      number:
        description: "PR/Issue number (for comments)"
        required: false
      title:
        description: "Title (for open-issue OR open-pr)"
        required: false
      body:
        description: "Body text (markdown or code)"
        required: false
      base:
        description: "Base branch (for open-pr, e.g., main)"
        required: false
      head:
        description: "Head branch (for open-pr, e.g., feature/x or owner:feature/x)"
        required: false
      draft:
        description: "Draft PR? true|false (default false)"
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Banner
        shell: bash
        run: |
          echo "=== LearnStream Claude AI — start === $(date -u +%FT%TZ)"
          echo "actor=${{ github.actor }}"
          echo "action=${{ github.event.inputs.action }}"
          echo "target_repo_input='${{ github.event.inputs.target_repo }}'"

      - name: Mint installation token (GitHub App)
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.CLAUDE_AI_APP_ID }}
          private_key: ${{ secrets.CLAUDE_AI_APP_PRIVATE_KEY }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.CLAUDE_AI_INSTALLATION_ID }}

      - name: Compute target repo
        id: target
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${{ github.event.inputs.target_repo }}" ]; then
            echo "repo=${{ github.repository }}" >> "$GITHUB_OUTPUT"
          else
            echo "repo=${{ github.event.inputs.target_repo }}" >> "$GITHUB_OUTPUT"
          fi
          echo "Using repo: ${{ steps.target.outputs.repo }}"

      - name: "Sanity: token + repo visibility (20s each)"
        shell: bash
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
          REPO:  ${{ steps.target.outputs.repo }}
        run: |
          set -euo pipefail
          echo "::group::rate_limit"
          timeout 20s curl -fsS -H "Authorization: token $TOKEN" https://api.github.com/rate_limit > /dev/null \
            || { echo "rate_limit check failed"; exit 1; }
          echo "rate_limit OK"
          echo "::endgroup::"
          echo "::group::repo GET"
          CODE=$(timeout 20s curl -fsS -o /tmp/repo.json -w "%{http_code}" \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO") || { echo "curl error repos/$REPO"; exit 1; }
          echo "HTTP $CODE"; head -c 300 /tmp/repo.json || true; echo
          [ "$CODE" = "200" ] || { echo "Installation token cannot access $REPO"; exit 1; }
          echo "::endgroup::"

      - name: Dispatch action (open-issue / pr-comment / issue-comment / pr-code / open-pr)
        shell: bash
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
          REPO:  ${{ steps.target.outputs.repo }}
          ACT:   ${{ github.event.inputs.action }}
          NUM:   ${{ github.event.inputs.number }}
          TITLE: ${{ github.event.inputs.title }}
          BODY:  ${{ github.event.inputs.body }}
          BASE:  ${{ github.event.inputs.base }}
          HEAD:  ${{ github.event.inputs.head }}
          DRAFT: ${{ github.event.inputs.draft }}
          ACTOR: ${{ github.actor }}
        run: |
          set -euo pipefail
          echo "Dispatching action: $ACT"

          # Minimal provenance block with real newlines (no assistant, no timestamp/helper)
          PVT="$(cat <<'EOF'
          <!-- AI-PROVENANCE: DO NOT EDIT -->
          initiated-by: @__ACTOR__
          EOF
          )"
          PVT="${PVT/__ACTOR__/${ACTOR}}"

          # Build BODY with real newlines (prevents literal \n showing in UI)
          BODY_JOINED="$(printf '%s\n\n%s' "$PVT" "${BODY:-}")"

          case "$ACT" in
            open-issue)
              [ -z "${TITLE}" ] && { echo "Missing 'title' for open-issue"; exit 1; }
              payload=$(jq -nc \
                --arg title "$TITLE" \
                --arg body  "$BODY_JOINED" \
                '{title:$title, body:$body, labels:["ai"]}')
              echo "::group::POST /issues"
              CODE=$(curl -fsS -o /tmp/out.json -w "%{http_code}" \
                -X POST \
                -H "Authorization: token ${TOKEN}" \
                -H "Accept: application/vnd.github+json" \
                -H "Content-Type: application/json" \
                --data "$payload" \
                "https://api.github.com/repos/${REPO}/issues") || { echo "curl error creating issue"; exit 1; }
              echo "HTTP $CODE"; cat /tmp/out.json; echo
              [ "$CODE" -ge 200 ] && [ "$CODE" -lt 300 ] || exit 1
              echo "::endgroup::"
              ;;

            pr-comment|issue-comment)
              [ -z "${NUM}" ] && { echo "Missing 'number' for ${ACT}"; exit 1; }
              payload=$(jq -nc --arg b "$BODY_JOINED" '{body:$b}')
              echo "::group::POST /issues/$NUM/comments"
              CODE=$(curl -fsS -o /tmp/out.json -w "%{http_code}" \
                -X POST \
                -H "Authorization: token ${TOKEN}" \
                -H "Accept: application/vnd.github+json" \
                -H "Content-Type: application/json" \
                --data "$payload" \
                "https://api.github.com/repos/${REPO}/issues/${NUM}/comments") || { echo "curl error posting comment"; exit 1; }
              echo "HTTP $CODE"; cat /tmp/out.json; echo
              [ "$CODE" -ge 200 ] && [ "$CODE" -lt 300 ] || exit 1
              echo "::endgroup::"
              ;;

            pr-code)
              [ -z "${NUM}" ] && { echo "Missing 'number' for pr-code"; exit 1; }
              CODE_BODY="$(printf '%s\n\n```diff\n%s\n```' "$PVT" "${BODY:-}")"
              payload=$(jq -nc --arg b "$CODE_BODY" '{body:$b}')
              echo "::group::POST /issues/$NUM/comments (code)"
              CODE=$(curl -fsS -o /tmp/out.json -w "%{http_code}" \
                -X POST \
                -H "Authorization: token ${TOKEN}" \
                -H "Accept: application/vnd.github+json" \
                -H "Content-Type: application/json" \
                --data "$payload" \
                "https://api.github.com/repos/${REPO}/issues/${NUM}/comments") || { echo "curl error posting code comment"; exit 1; }
              echo "HTTP $CODE"; cat /tmp/out.json; echo
              [ "$CODE" -ge 200 ] && [ "$CODE" -lt 300 ] || exit 1
              echo "::endgroup::"
              ;;

            open-pr)
              [ -z "${TITLE}" ] && { echo "Missing 'title' for open-pr"; exit 1; }
              [ -z "${BASE}" ] && { echo "Missing 'base' branch for open-pr"; exit 1; }
              [ -z "${HEAD}" ] && { echo "Missing 'head' branch for open-pr"; exit 1; }
              # normalize DRAFT to boolean
              case "${DRAFT}" in true|false) : ;; *) DRAFT="false";; esac
              payload=$(jq -nc \
                --arg title "$TITLE" \
                --arg body  "$BODY_JOINED" \
                --arg base  "$BASE" \
                --arg head  "$HEAD" \
                --argjson draft ${DRAFT:-false} \
                '{title:$title, body:$body, base:$base, head:$head, draft:$draft}')
              echo "::group::POST /pulls"
              CODE=$(curl -fsS -o /tmp/out.json -w "%{http_code}" \
                -X POST \
                -H "Authorization: token ${TOKEN}" \
                -H "Accept: application/vnd.github+json" \
                -H "Content-Type: application/json" \
                --data "$payload" \
                "https://api.github.com/repos/${REPO}/pulls") || { echo "curl error creating PR"; exit 1; }
              echo "HTTP $CODE"; cat /tmp/out.json; echo
              [ "$CODE" -ge 200 ] && [ "$CODE" -lt 300 ] || exit 1
              echo "::endgroup::"
              ;;

            *)
              echo "Unknown action: $ACT"; exit 1;;
          esac

      - name: Done
        run: echo "=== LearnStream Claude AI — done === $(date -u +%FT%TZ)"
